services:
  frontend:
    image: ghcr.io/cedrickring/cora-deploy/frontend:ecc52d935cd360164b34e968577b9eb32762f600
    environment:
      BACKEND_URL: "${BACKEND_URL}"
    ports:
      - "8080:8080"
  backend:
    image: ghcr.io/cedrickring/cora-deploy/backend:ecc52d935cd360164b34e968577b9eb32762f600
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      VECTOR_DATABASES_PATH: '/app/vector_databases'
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_TYPE: "${OPENAI_API_TYPE}"
      OPENAI_EMBEDDINGS_MODEL: "${OPENAI_EMBEDDINGS_MODEL}"
      OPENAI_GPT_MODEL: "${OPENAI_GPT_MODEL}"
      AZURE_EMBEDDINGS_DEPLOYMENT: "${AZURE_EMBEDDINGS_DEPLOYMENT}"
      AZURE_GPT_MODEL_DEPLOYMENT: "${AZURE_GPT_MODEL_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    ports:
      - "5001:5001"
  preprocessing:
    profiles: ["vectorize"]
    image: ghcr.io/cedrickring/cora-deploy/preprocessing:ecc52d935cd360164b34e968577b9eb32762f600
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      OUTPUT_FILES_PATH: '/app/vector_databases'
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_TYPE: "${OPENAI_API_TYPE}"
      OPENAI_EMBEDDINGS_MODEL: "${OPENAI_EMBEDDINGS_MODEL}"
      AZURE_EMBEDDINGS_DEPLOYMENT: "${AZURE_EMBEDDINGS_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    restart: no
