services:
  frontend:
    image: ghcr.io/cedrickring/cora-deploy/frontend:954b49786542d852ff6378a640dd239a7ac7ceb3
    ports:
      - "8080"
  backend:
    image: ghcr.io/cedrickring/cora-deploy/backend:954b49786542d852ff6378a640dd239a7ac7ceb3
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      VECTOR_DATABASES_PATH: '/app/vector_databases'
      AZURE_OPENAI_BASE: "${AZURE_OPENAI_BASE}"
      AZURE_OPENAI_KEY: "${AZURE_OPENAI_KEY}"
      AZURE_OPENAI_EMB_MODEL_NAME: "${AZURE_OPENAI_EMB_MODEL_NAME}"
      AZURE_OPENAI_EMB_DEPLOYMENT: "${AZURE_OPENAI_EMB_DEPLOYMENT}"
      AZURE_OPENAI_CHATGPT_MODEL: "${AZURE_OPENAI_CHATGPT_MODEL}"
      AZURE_OPENAI_CHATGPT_DEPLOYMENT: "${AZURE_OPENAI_CHATGPT_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    ports:
      - "5050"
  preprocessing:
    profiles: ["vectorize"]
    image: ghcr.io/cedrickring/cora-deploy/preprocessing:954b49786542d852ff6378a640dd239a7ac7ceb3
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      OUTPUT_FILES_PATH: '/app/vector_databases'
      AZURE_OPENAI_BASE: "${AZURE_OPENAI_BASE}"
      AZURE_OPENAI_KEY: "${AZURE_OPENAI_KEY}"
      AZURE_OPENAI_EMB_MODEL_NAME: "${AZURE_OPENAI_EMB_MODEL_NAME}"
      AZURE_OPENAI_EMB_DEPLOYMENT: "${AZURE_OPENAI_EMB_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    restart: no
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
