services:
  frontend:
    image: ghcr.io/cedrickring/cora-deploy/frontend:7dd605f9eb0de2b94e6171c54b681be6c676afe5
    ports:
      - "8080"
  backend:
    image: ghcr.io/cedrickring/cora-deploy/backend:7dd605f9eb0de2b94e6171c54b681be6c676afe5
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      VECTOR_DATABASES_PATH: '/app/vector_databases'
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_TYPE: "${OPENAI_API_TYPE}"
      OPENAI_EMBEDDINGS_MODEL: "${OPENAI_EMBEDDINGS_MODEL}"
      OPENAI_GPT_MODEL: "${OPENAI_GPT_MODEL}"
      AZURE_EMBEDDINGS_DEPLOYMENT: "${AZURE_EMBEDDINGS_DEPLOYMENT}"
      AZURE_GPT_MODEL_DEPLOYMENT: "${AZURE_GPT_MODEL_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    ports:
      - "5050"
  preprocessing:
    profiles: ["vectorize"]
    image: ghcr.io/cedrickring/cora-deploy/preprocessing:7dd605f9eb0de2b94e6171c54b681be6c676afe5
    environment:
      INPUT_FILES_PATH: "/app/input_files"
      OUTPUT_FILES_PATH: '/app/vector_databases'
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_TYPE: "${OPENAI_API_TYPE}"
      OPENAI_EMBEDDINGS_MODEL: "${OPENAI_EMBEDDINGS_MODEL}"
      AZURE_EMBEDDINGS_DEPLOYMENT: "${AZURE_EMBEDDINGS_DEPLOYMENT}"
    volumes:
      - ./input_files:/app/input_files
      - ./vector_databases:/app/vector_databases
    restart: no
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
